### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by stefnotch** [varkor/DISTORT#1]
It'd be lovely to see this project in action on GitHub pages. I think all you have to do is click on the settings tab, click on "pages" there and turn on GitHub pages from the master branch. After that, it should end up being visible at a URL like https://varkor.github.io/DISTORT

**Comment by varkor** [comment]
It's actually already available at http://varkor.com/games/distort/.

**Comment by stefnotch** [comment]
Yay, awesome! Would it be reasonable to link to that page from the GitHub repo?

**Comment by varkor** [comment]
Thanks for the suggestion, I have done so.
